# Introduction

In [7]:
import zypy_debug as zp

x1 = zp.allocate(shape=(10000,), dtype="f4")
x1[:] = zp.arange(x1.size)

x2 = zp.allocate(shape=(10000,), dtype="f4")
x2[:] = zp.arange(x2.size)

print(x1)
print(x2)

[0.000e+00 1.000e+00 2.000e+00 ... 9.997e+03 9.998e+03 9.999e+03]
[0.000e+00 1.000e+00 2.000e+00 ... 9.997e+03 9.998e+03 9.999e+03]


In [8]:
x1 + x2

ufunc `add.__call__` called
Checking implementation `/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_call_f4.bit`
Bitfile loaded = False
Checking implementation `/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_call_i4.bit`
Running default


array([0.0000e+00, 2.0000e+00, 4.0000e+00, ..., 1.9994e+04, 1.9996e+04,
       1.9998e+04], dtype=float32)

In [9]:
zp.hint("add.__call__", x1, x2)

'/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_call_f4.bit'

In [10]:
x1 + x2

ufunc `add.__call__` called
Checking implementation `/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_call_f4.bit`
Bitfile loaded = True
`add.__call__` can be accelerated using driver `<function ZyPy.add_call_f4_cffi at 0xb00dca08>`
Allocated fresh `out` argument
Runnning hardware accelerator!


PynqBuffer([0.0000e+00, 2.0000e+00, 4.0000e+00, ..., 1.9994e+04,
            1.9996e+04, 1.9998e+04], dtype=float32)

# Other operations

In [11]:
zp.hint("add.reduce", x1, axis=None)
print(zp.add.reduce(x1, axis=None))

ufunc `add.reduce` called
Checking implementation `/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_reduce_all_f4.bit`
Bitfile loaded = True
`add.reduce` can be accelerated using driver `<function ZyPy.add_reduce_all_f4_cffi at 0xaf579f18>`
Runnning hardware accelerator!
49995000.0


In [12]:
zp.hint("dot", x1, x2)
zp.dot(x1, x2)

method `<class 'numpy.ufunc'>` called
Checking implementation `/home/xilinx/jupyter_notebooks/zypy/overlays/ufunc_reduce_all_f4.bit`
Bitfile loaded = True
`dot` can be accelerated using driver `<function ZyPy.dot_f4_cffi at 0xaf4fd108>`
Runnning hardware accelerator (pre-alloc)!


333283328000.0